"""Add ArticleReaction model for likes and AI comments

Revision ID: 394457255624
Revises: bfa606d79bbb
Create Date: 2025-10-27 09:38:19.827384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394457255624'
down_revision = 'bfa606d79bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('liked', sa.Boolean(), nullable=False),
    sa.Column('ai_comment', sa.Text(), nullable=True),
    sa.Column('date_reacted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_reaction')
    # ### end Alembic commands ###
