"""Remove AI comments and add user comments system

Revision ID: e782c5cdf1f1
Revises: 394457255624
Create Date: 2025-10-27 09:43:10.506026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e782c5cdf1f1'
down_revision = '394457255624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_reaction', schema=None) as batch_op:
        batch_op.drop_column('ai_comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_reaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_comment', sa.TEXT(), nullable=True))

    op.drop_table('comment')
    # ### end Alembic commands ###
